import { Inter } from "next/font/google";
import Head from "next/head"; // Import the Head component
import "./globals.css";
import Link from "next/link";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "California Pub",
  description: "Generated by create next app",
  icon:"./icon.ico"
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <Head>
        <title></title>
        <meta name="description" content={metadata.description} />
        <Link rel="icon" href={metadata.icon} />
      </Head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
