import { Inter } from "next/font/google";
import Head from "next/head"; // Import the Head component
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "California Pub",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        {/* <link rel="icon" href="/favicon.ico" />{" "} */}
        <link rel="icon" href="/public/assets/images/logo.ico" />{" "}
        {/* Adjust the path as needed */}
        {/* Add more metadata as needed */}
      </Head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
